# Generated by Django 4.1.3 on 2022-11-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Novaya'), ('in_progress', 'V processe'), ('done', 'Sdelano')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
